allowBuilds:
  '@google/genai': true
  core-js: true
  esbuild: true
  msw: true
  protobufjs: true
  unrs-resolver: true
overrides:
  '@vitest/mocker@>=2.1.0 <4.1.11': ^4.1.11
  esbuild@<=0.24.2: ^0.25.0
  vitest@>=2.1.0 <4.1.11: ^4.1.11
  better-call: 1.4.0
